"""Synthetic candidate profile and documents for WQ-7 dry-runs.

All data is explicitly synthetic — no real candidate PII is used.
The synthetic documents are clearly marked as test data and are
generated temporarily (never committed to the repository).

Safety:
- Name clearly identifies test automation.
- Email uses example.com (RFC 2606 reserved domain).
- Phone is a non-real test value.
- No real LinkedIn account, profile, passwords, cookies, or API credentials.
- Never fabricates sensitive answers as if they belong to the real user.
- CV and cover letter PDFs visibly state "TEST DATA — AUTOMATION DRY RUN".
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path

logger = logging.getLogger("universal_auto_applier.synthetic_profile")

# Minimal PDF content with visible "TEST DATA" watermark.
# This is a valid minimal PDF that any ATS file-type check will accept.
_PDF_TEMPLATE = """%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]/Contents 4 0 R/Resources<</Font<</F1 5 0 R>>>>>>endobj
4 0 obj<</Length {length}>>stream
BT /F1 24 Tf 72 700 Td ({title}) Tj ET
BT /F1 14 Tf 72 660 Td (TEST DATA - AUTOMATION DRY RUN - NOT A REAL APPLICATION) Tj ET
BT /F1 12 Tf 72 630 Td (This document was generated by UniversalAutoApplier WQ-7.) Tj ET
BT /F1 12 Tf 72 610 Td (It contains no real candidate data.) Tj ET
BT /F1 12 Tf 72 590 Td (Do not process this as a real application.) Tj ET
endstream endobj
5 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj
xref
0 6
0000000000 65535 f
0000000009 00000 n
0000000052 00000 n
0000000095 00000 n
0000000178 00000 n
0000000{content_offset} 00000 n
trailer<</Size 6/Root 1 0 R>>
startxref
{xref_offset}
%%EOF
"""


@dataclass(frozen=True)
class SyntheticProfile:
    """Synthetic candidate profile for WQ-7 dry-runs.

    All fields are explicitly synthetic. No real PII.
    """

    first_name: str = "Test"
    last_name: str = "Automation"
    full_name: str = "Test Automation"
    email: str = "test.automation@example.com"
    phone: str = "+1 555 0100"
    city: str = "Test City"
    country: str = "United States"
    linkedin: str = ""  # Empty — no real LinkedIn profile is used in WQ-7
    website: str = "https://example.com/test-automation"
    requires_sponsorship: bool = False
    years_of_experience: str = "5"
    current_role: str = "Software Engineer (Test)"
    wq7_synthetic: bool = True

    def to_metadata(self) -> dict[str, object]:
        """Convert to job metadata format (matching candidate_profile structure)."""
        return {
            "candidate_profile": {
                "first_name": self.first_name,
                "last_name": self.last_name,
                "full_name": self.full_name,
                "email": self.email,
                "phone": self.phone,
                "city": self.city,
                "country": self.country,
                "linkedin": self.linkedin,
                "website": self.website,
                "requires_sponsorship": self.requires_sponsorship,
                "years_of_experience": self.years_of_experience,
                "current_role": self.current_role,
                "wq7_synthetic": True,
            },
        }


def generate_synthetic_cv(output_path: Path) -> Path:
    """Generate a synthetic CV PDF with visible TEST DATA marking.

    The PDF is a valid minimal PDF that passes ATS file-type checks.
    It contains no real candidate data.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    # Build a simple valid PDF
    content = (
        "BT /F1 24 Tf 72 700 Td (Test Automation - CV) Tj ET\n"
        "BT /F1 14 Tf 72 660 Td "
        "(TEST DATA - AUTOMATION DRY RUN - NOT A REAL APPLICATION) Tj ET\n"
        "BT /F1 12 Tf 72 630 Td "
        "(Generated by UniversalAutoApplier WQ-7) Tj ET\n"
        "BT /F1 12 Tf 72 610 Td (No real candidate data.) Tj ET\n"
        "BT /F1 12 Tf 72 590 Td (Do not process as a real application.) Tj ET"
    )
    pdf = _build_minimal_pdf(content, "Test Automation - CV")
    output_path.write_bytes(pdf)
    logger.info("[wq7] Synthetic CV generated: %s", output_path)
    return output_path


def generate_synthetic_cover_letter(output_path: Path) -> Path:
    """Generate a synthetic cover letter PDF with visible TEST DATA marking."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    content = (
        "BT /F1 24 Tf 72 700 Td (Test Automation - Cover Letter) Tj ET\n"
        "BT /F1 14 Tf 72 660 Td "
        "(TEST DATA - AUTOMATION DRY RUN - NOT A REAL APPLICATION) Tj ET\n"
        "BT /F1 12 Tf 72 630 Td (Generated by UniversalAutoApplier WQ-7) Tj ET\n"
        "BT /F1 12 Tf 72 610 Td (No real candidate data.) Tj ET"
    )
    pdf = _build_minimal_pdf(content, "Test Automation - Cover Letter")
    output_path.write_bytes(pdf)
    logger.info("[wq7] Synthetic cover letter generated: %s", output_path)
    return output_path


def _build_minimal_pdf(content_stream: str, title: str) -> bytes:
    """Build a minimal valid PDF with the given content stream."""
    # This constructs a minimal but valid PDF.
    objects: list[str] = []

    # Object 1: Catalog
    objects.append("1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n")
    # Object 2: Pages
    objects.append("2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\n")
    # Object 3: Page
    objects.append(
        "3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]"
        "/Contents 4 0 R/Resources<</Font<</F1 5 0 R>>>>>>endobj\n"
    )
    # Object 4: Content stream
    stream_len = len(content_stream)
    objects.append(f"4 0 obj<</Length {stream_len}>>stream\n{content_stream}\nendstream endobj\n")
    # Object 5: Font
    objects.append("5 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj\n")

    # Build xref
    pdf_parts: list[bytes] = [b"%PDF-1.4\n"]
    offsets: list[int] = []
    for obj in objects:
        offsets.append(len(b"".join(pdf_parts)))
        pdf_parts.append(obj.encode("ascii"))

    xref_offset = len(b"".join(pdf_parts))
    xref_lines = ["xref\n", f"0 {len(objects) + 1}\n", "0000000000 65535 f \n"]
    for offset in offsets:
        xref_lines.append(f"{offset:010d} 00000 n \n")
    xref_lines.append(
        f"trailer<</Size {len(objects) + 1}/Root 1 0 R>>\nstartxref\n{xref_offset}\n%%EOF\n"
    )
    pdf_parts.append("".join(xref_lines).encode("ascii"))

    return b"".join(pdf_parts)


def create_synthetic_documents(directory: Path) -> tuple[Path, Path]:
    """Create synthetic CV and cover letter in the given directory.

    Returns (cv_path, cover_letter_path).
    """
    cv_path = generate_synthetic_cv(directory / "wq7-test-cv.pdf")
    cover_path = generate_synthetic_cover_letter(directory / "wq7-test-cover.pdf")
    return cv_path, cover_path


__all__ = [
    "SyntheticProfile",
    "create_synthetic_documents",
    "generate_synthetic_cover_letter",
    "generate_synthetic_cv",
]
