"""Synthetic candidate profile and documents for WQ-7 dry-runs.

All data is explicitly synthetic — no real candidate PII is used.
The synthetic documents are clearly marked as test data and are
generated temporarily (never committed to the repository).

Safety:
- Name clearly identifies test automation.
- Email uses example.com (RFC 2606 reserved domain).
- Phone is a non-real test value.
- No real LinkedIn account, profile, passwords, cookies, or API credentials.
- Never fabricates sensitive answers as if they belong to the real user.
- CV and cover letter PDFs visibly state "TEST DATA — AUTOMATION DRY RUN".

WQ-7C synthetic mutation:
- A dedicated :class:`SyntheticMutationProfile` carries the required
  ``synthetic_test=True`` / ``wq7_synthetic=True`` markers so operation code
  can refuse to run WQ-7C mutation against a normal candidate.
- Synthetic mutation documents carry the stronger banner
  ``SYNTHETIC TEST DOCUMENT / NOT A REAL CANDIDATE / DO NOT PROCESS AS AN
  APPLICATION`` and are hash-verifiable so the production mutation path only
  ever uploads approved synthetic files.
"""

from __future__ import annotations

import hashlib
import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Any, cast

logger = logging.getLogger("universal_auto_applier.synthetic_profile")

# WQ-7C banner that MUST appear on every synthetic mutation document so the
# document cannot be mistaken for a real candidate's CV even by a human.
SYNTHETIC_MUTATION_BANNER = (
    "SYNTHETIC TEST DOCUMENT / NOT A REAL CANDIDATE / DO NOT PROCESS AS AN APPLICATION"
)

# Minimal PDF content with visible "TEST DATA" watermark.
# This is a valid minimal PDF that any ATS file-type check will accept.
_PDF_TEMPLATE = """%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]/Contents 4 0 R/Resources<</Font<</F1 5 0 R>>>>>>endobj
4 0 obj<</Length {length}>>stream
BT /F1 24 Tf 72 700 Td ({title}) Tj ET
BT /F1 14 Tf 72 660 Td (TEST DATA - AUTOMATION DRY RUN - NOT A REAL APPLICATION) Tj ET
BT /F1 12 Tf 72 630 Td (This document was generated by UniversalAutoApplier WQ-7.) Tj ET
BT /F1 12 Tf 72 610 Td (It contains no real candidate data.) Tj ET
BT /F1 12 Tf 72 590 Td (Do not process this as a real application.) Tj ET
endstream endobj
5 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj
xref
0 6
0000000000 65535 f
0000000009 00000 n
0000000052 00000 n
0000000095 00000 n
0000000178 00000 n
0000000{content_offset} 00000 n
trailer<</Size 6/Root 1 0 R>>
startxref
{xref_offset}
%%EOF
"""


@dataclass(frozen=True)
class SyntheticProfile:
    """Synthetic candidate profile for WQ-7 dry-runs.

    All fields are explicitly synthetic. No real PII.
    """

    first_name: str = "Test"
    last_name: str = "Automation"
    full_name: str = "Test Automation"
    email: str = "test.automation@example.com"
    phone: str = "+1 555 0100"
    city: str = "Test City"
    country: str = "United States"
    linkedin: str = ""  # Empty — no real LinkedIn profile is used in WQ-7
    website: str = "https://example.com/test-automation"
    requires_sponsorship: bool = False
    years_of_experience: str = "5"
    current_role: str = "Software Engineer (Test)"
    wq7_synthetic: bool = True

    def to_metadata(self) -> dict[str, object]:
        """Convert to job metadata format (matching candidate_profile structure)."""
        return {
            "candidate_profile": {
                "first_name": self.first_name,
                "last_name": self.last_name,
                "full_name": self.full_name,
                "email": self.email,
                "phone": self.phone,
                "city": self.city,
                "country": self.country,
                "linkedin": self.linkedin,
                "website": self.website,
                "requires_sponsorship": self.requires_sponsorship,
                "years_of_experience": self.years_of_experience,
                "current_role": self.current_role,
                "wq7_synthetic": True,
            },
        }


@dataclass(frozen=True)
class SyntheticMutationProfile:
    """Dedicated WQ-7C synthetic mutation identity.

    Structurally distinct from the WQ-7A/B SyntheticProfile so that
    operation code can require the exact ``synthetic_test`` marker and
    refuse to run synthetic mutation against any other candidate data:

    - ``synthetic_test: True`` and ``wq7_synthetic: True`` markers,
    - ``first_name=Test`` / ``last_name=Candidate``,
    - ``example.com`` (RFC 2606) email,
    - fictional ``+1 555 0199`` phone that no real subscriber owns,
    - no real LinkedIn profile / website / credentials.

    It is consumed ONLY by the WQ-7C opt-in synthetic mutation path. It is
    never the default candidate and is never used for real submissions.
    """

    first_name: str = "Test"
    last_name: str = "Candidate"
    full_name: str = "Test Candidate"
    email: str = "test.candidate@example.com"
    phone: str = "+1 555 0199"
    city: str = "Test City"
    country: str = "Syntheticland"
    linkedin: str = ""  # Empty — never a real profile.
    website: str = "https://example.com/test-candidate"
    requires_sponsorship: bool = False
    years_of_experience: int = 5
    current_role: str = "Synthetic Test Engineer"
    synthetic_test: bool = True
    wq7_synthetic: bool = True

    def to_metadata(self) -> dict[str, object]:
        """Convert to job metadata (matching candidate_profile structure)."""
        return {
            "candidate_profile": {
                "first_name": self.first_name,
                "last_name": self.last_name,
                "full_name": self.full_name,
                "email": self.email,
                "phone": self.phone,
                "city": self.city,
                "country": self.country,
                "linkedin": self.linkedin,
                "website": self.website,
                "requires_sponsorship": self.requires_sponsorship,
                "years_of_experience": self.years_of_experience,
                "current_role": self.current_role,
                "synthetic_test": True,
                "wq7_synthetic": True,
            },
        }

    def to_candidate_profile(self) -> Any:
        """Convert into the core :class:`CandidateProfile` used by mappers.

        The ``linkedin``/``website`` fields map to their URL counterparts;
        notably ``linkedin`` stays empty so the mapper never proposes a real
        profile URL.
        """
        from universal_auto_applier.core.models import CandidateProfile

        return CandidateProfile(
            first_name=self.first_name,
            last_name=self.last_name,
            full_name=self.full_name,
            email=self.email,
            phone=self.phone,
            city=self.city,
            country=self.country,
            requires_sponsorship=self.requires_sponsorship,
            years_of_experience=self.years_of_experience,
            current_position=self.current_role,
            linkedin_url=self.linkedin or None,
            website=self.website,
        )


def sha256_file(path: Path) -> str:
    """Return the lowercase SHA-256 hexdigest of ``path``'s bytes."""
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 16), b""):
            digest.update(chunk)
    return digest.hexdigest()


def generate_synthetic_mutation_cv(output_path: Path) -> Path:
    """Generate a WQ-7C synthetic CV PDF with the strong synthetic banner.

    The PDF is a valid minimal PDF that passes ATS file-type checks and
    visibly states ``SYNTHETIC TEST DOCUMENT / NOT A REAL CANDIDATE /
    DO NOT PROCESS AS AN APPLICATION`` so it cannot be mistaken for a real
    candidate's document.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    content = (
        "BT /F1 24 Tf 72 700 Td (Test Candidate - Synthetic CV) Tj ET\n"
        "BT /F1 14 Tf 72 660 Td "
        "(SYNTHETIC TEST DOCUMENT / NOT A REAL CANDIDATE / \\n) Tj ET\n"
        "BT /F1 14 Tf 72 645 Td "
        "(DO NOT PROCESS AS AN APPLICATION) Tj ET\n"
        "BT /F1 12 Tf 72 615 Td "
        "(Generated by UniversalAutoApplier WQ-7C synthetic mutation.) Tj ET\n"
        "BT /F1 12 Tf 72 595 Td "
        "(Contains no real candidate data.) Tj ET"
    )
    pdf = _build_minimal_pdf(content, "Synthetic CV - Test Candidate")
    output_path.write_bytes(pdf)
    logger.info("[wq7c] Synthetic mutation CV generated: %s", output_path)
    return output_path


def generate_synthetic_mutation_cover(output_path: Path) -> Path:
    """Generate a WQ-7C synthetic cover letter PDF with the strong banner."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    content = (
        "BT /F1 24 Tf 72 700 Td (Test Candidate - Synthetic Cover Letter) Tj ET\n"
        "BT /F1 14 Tf 72 660 Td "
        "(SYNTHETIC TEST DOCUMENT / NOT A REAL CANDIDATE / \\n) Tj ET\n"
        "BT /F1 14 Tf 72 645 Td "
        "(DO NOT PROCESS AS AN APPLICATION) Tj ET\n"
        "BT /F1 12 Tf 72 615 Td "
        "(Generated by UniversalAutoApplier WQ-7C synthetic mutation.) Tj ET\n"
        "BT /F1 12 Tf 72 595 Td "
        "(Contains no real candidate data.) Tj ET"
    )
    pdf = _build_minimal_pdf(content, "Synthetic Cover Letter - Test Candidate")
    output_path.write_bytes(pdf)
    logger.info("[wq7c] Synthetic mutation cover generated: %s", output_path)
    return output_path


def create_synthetic_mutation_documents(directory: Path) -> tuple[Path, Path]:
    """Create WQ-7C synthetic CV and cover letter (strongly marked).

    Returns ``(cv_path, cover_path)``.
    """
    cv_path = generate_synthetic_mutation_cv(directory / "wq7c-test-cv.pdf")
    cover_path = generate_synthetic_mutation_cover(directory / "wq7c-test-cover.pdf")
    return cv_path, cover_path


def approved_document_hashes(*paths: Path) -> frozenset[str]:
    """Return a frozen set of SHA-256 hashes for the approved synthetic docs.

    The mutation enforcement layer compares every proposed upload against
    this set before ``set_input_files`` is allowed.
    """
    return frozenset(sha256_file(path) for path in paths if path.exists())


def is_synthetic_metadata(metadata: dict[str, Any] | None) -> bool:
    """True when the candidate snapshot in ``metadata`` carries the WQ-7C marker.

    WQ-7C mutation refuses to run against a normal candidate. ``metadata``
    is the ``ApplicationJob.metadata`` dict; the candidate snapshot is the
    ``candidate_profile`` key. The marker is accepted in either the
    ``synthetic_test`` or ``wq7_synthetic`` form (both are written by
    :class:`SyntheticMutationProfile`).
    """
    if not metadata:
        return False
    snapshot = metadata.get("candidate_profile")
    if not isinstance(snapshot, dict):
        return False
    snapshot_typed: dict[str, object] = cast(dict[str, object], snapshot)
    return bool(snapshot_typed.get("synthetic_test") or snapshot_typed.get("wq7_synthetic"))


def is_synthetic_identity_snapshot(snapshot: Any) -> bool:
    """True when ``candidate_profile`` matches the WQ-7C synthetic identity.

    Both the full name and the RFC 2606 email must match
    :class:`SyntheticMutationProfile` exactly. This is the identity guard
    for the opt-in ``queue-import --synthetic-mutation`` stamp: markers are
    only ever written onto a snapshot that already IS the synthetic identity.
    """
    if not isinstance(snapshot, dict):
        return False
    snapshot_typed: dict[str, object] = cast(dict[str, object], snapshot)
    return bool(
        snapshot_typed.get("full_name") == SyntheticMutationProfile.full_name
        and snapshot_typed.get("email") == SyntheticMutationProfile.email
    )


def stamp_synthetic_mutation_metadata(metadata: dict[str, Any]) -> dict[str, Any]:
    """Return a copy of ``metadata`` with WQ-7C synthetic markers stamped.

    Only stamps when the ``candidate_profile`` snapshot already matches the
    WQ-7C synthetic identity (see :func:`is_synthetic_identity_snapshot`).
    Marker stamping is opt-in (``queue-import --synthetic-mutation``); it is
    never applied to a snapshot that could belong to a real candidate.

    Returns:
        A shallow-copied ``metadata`` dict whose ``candidate_profile`` carries
        ``synthetic_test=True`` and ``wq7_synthetic=True``.

    Raises:
        ValueError: If the snapshot is missing, not a dict, or does not match
            the WQ-7C synthetic identity.
    """
    snapshot = metadata.get("candidate_profile")
    if not is_synthetic_identity_snapshot(snapshot):
        raise ValueError(
            "candidate_profile does not match the WQ-7C synthetic identity "
            f"({SyntheticMutationProfile.full_name} / {SyntheticMutationProfile.email}); "
            "refusing to stamp synthetic-mutation markers"
        )
    snapshot_typed = cast(dict[str, object], snapshot)
    stamped_snapshot: dict[str, object] = dict(snapshot_typed)
    stamped_snapshot["synthetic_test"] = True
    stamped_snapshot["wq7_synthetic"] = True
    stamped_metadata: dict[str, Any] = dict(metadata)
    stamped_metadata["candidate_profile"] = stamped_snapshot
    return stamped_metadata


def generate_synthetic_cv(output_path: Path) -> Path:
    """Generate a synthetic CV PDF with visible TEST DATA marking.

    The PDF is a valid minimal PDF that passes ATS file-type checks.
    It contains no real candidate data.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    # Build a simple valid PDF
    content = (
        "BT /F1 24 Tf 72 700 Td (Test Automation - CV) Tj ET\n"
        "BT /F1 14 Tf 72 660 Td "
        "(TEST DATA - AUTOMATION DRY RUN - NOT A REAL APPLICATION) Tj ET\n"
        "BT /F1 12 Tf 72 630 Td "
        "(Generated by UniversalAutoApplier WQ-7) Tj ET\n"
        "BT /F1 12 Tf 72 610 Td (No real candidate data.) Tj ET\n"
        "BT /F1 12 Tf 72 590 Td (Do not process as a real application.) Tj ET"
    )
    pdf = _build_minimal_pdf(content, "Test Automation - CV")
    output_path.write_bytes(pdf)
    logger.info("[wq7] Synthetic CV generated: %s", output_path)
    return output_path


def generate_synthetic_cover_letter(output_path: Path) -> Path:
    """Generate a synthetic cover letter PDF with visible TEST DATA marking."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    content = (
        "BT /F1 24 Tf 72 700 Td (Test Automation - Cover Letter) Tj ET\n"
        "BT /F1 14 Tf 72 660 Td "
        "(TEST DATA - AUTOMATION DRY RUN - NOT A REAL APPLICATION) Tj ET\n"
        "BT /F1 12 Tf 72 630 Td (Generated by UniversalAutoApplier WQ-7) Tj ET\n"
        "BT /F1 12 Tf 72 610 Td (No real candidate data.) Tj ET"
    )
    pdf = _build_minimal_pdf(content, "Test Automation - Cover Letter")
    output_path.write_bytes(pdf)
    logger.info("[wq7] Synthetic cover letter generated: %s", output_path)
    return output_path


def _build_minimal_pdf(content_stream: str, title: str) -> bytes:
    """Build a minimal valid PDF with the given content stream."""
    # This constructs a minimal but valid PDF.
    objects: list[str] = []

    # Object 1: Catalog
    objects.append("1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n")
    # Object 2: Pages
    objects.append("2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\n")
    # Object 3: Page
    objects.append(
        "3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]"
        "/Contents 4 0 R/Resources<</Font<</F1 5 0 R>>>>>>endobj\n"
    )
    # Object 4: Content stream
    stream_len = len(content_stream)
    objects.append(f"4 0 obj<</Length {stream_len}>>stream\n{content_stream}\nendstream endobj\n")
    # Object 5: Font
    objects.append("5 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj\n")

    # Build xref
    pdf_parts: list[bytes] = [b"%PDF-1.4\n"]
    offsets: list[int] = []
    for obj in objects:
        offsets.append(len(b"".join(pdf_parts)))
        pdf_parts.append(obj.encode("ascii"))

    xref_offset = len(b"".join(pdf_parts))
    xref_lines = ["xref\n", f"0 {len(objects) + 1}\n", "0000000000 65535 f \n"]
    for offset in offsets:
        xref_lines.append(f"{offset:010d} 00000 n \n")
    xref_lines.append(
        f"trailer<</Size {len(objects) + 1}/Root 1 0 R>>\nstartxref\n{xref_offset}\n%%EOF\n"
    )
    pdf_parts.append("".join(xref_lines).encode("ascii"))

    return b"".join(pdf_parts)


def create_synthetic_documents(directory: Path) -> tuple[Path, Path]:
    """Create synthetic CV and cover letter in the given directory.

    Returns (cv_path, cover_letter_path).
    """
    cv_path = generate_synthetic_cv(directory / "wq7-test-cv.pdf")
    cover_path = generate_synthetic_cover_letter(directory / "wq7-test-cover.pdf")
    return cv_path, cover_path


__all__ = [
    "SYNTHETIC_MUTATION_BANNER",
    "SyntheticMutationProfile",
    "SyntheticProfile",
    "approved_document_hashes",
    "create_synthetic_documents",
    "create_synthetic_mutation_documents",
    "generate_synthetic_cover_letter",
    "generate_synthetic_cv",
    "generate_synthetic_mutation_cover",
    "generate_synthetic_mutation_cv",
    "is_synthetic_identity_snapshot",
    "is_synthetic_metadata",
    "sha256_file",
    "stamp_synthetic_mutation_metadata",
]
