"""AI Supervisor (agent-assisted operator mode V0) — domain models.

Typed contracts for the supervisor layer. The supervisor is an LLM-driven
operator that drives UAA ONLY through the safe typed tool layer
(:mod:`universal_auto_applier.supervisor.tools`); it never receives raw
browser control and it can never submit (there is no SUBMITTED state and no
submit/authorization action anywhere in this module).
"""

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field, field_validator


class SupervisorState(StrEnum):
    """Supervisor-level state for one application.

    Deliberately distinct from :class:`ApplicationStatus` (the UAA job
    lifecycle). There is NO ``SUBMITTED`` state in V0 — an application that
    reaches ``REVIEW_READY`` stops and waits for the human owner.
    """

    IMPORTED = "imported"
    PREPARING = "preparing"
    RUNNING = "running"
    WAITING_FOR_INTERVENTION = "waiting_for_intervention"
    RETRY_PENDING = "retry_pending"
    REVIEW_READY = "review_ready"
    NEEDS_HUMAN = "needs_human"
    REPAIR_NEEDED = "repair_needed"
    BLOCKED = "blocked"
    SKIPPED = "skipped"
    FAILED = "failed"


class SupervisorAction(StrEnum):
    """The complete set of actions a supervisor planner may request.

    No submit action, no authorization action, no raw browser action
    exists. Any other action name is invalid model output and fails closed.
    """

    RESOLVE_INTERVENTION = "resolve_intervention"
    RETRY_APPLICATION = "retry_application"
    REQUEST_HUMAN = "request_human"
    CREATE_REPAIR_TICKET = "create_repair_ticket"
    MARK_REVIEW_READY = "mark_review_ready"
    SKIP_APPLICATION = "skip_application"
    STOP = "stop"


class AnswerSource(StrEnum):
    """Which knowledge level produced an answer (three knowledge levels + provenance)."""

    # Stable factual profile data (candidate facts).
    CANDIDATE_FACT = "candidate_fact"
    # Reusable owner-approved decisions/policies.
    OWNER_POLICY = "owner_policy"
    # Only valid for this one application (owner-supplied job answer).
    JOB_SPECIFIC = "job_specific"
    # Existing approved answer memory (exact normalized-question match).
    ANSWER_MEMORY = "answer_memory"
    # The human owner supplied the answer directly.
    HUMAN = "human"
    # Model inference — strictly restricted (low-risk questions only).
    MODEL_INFERENCE = "model_inference"


class ReasonCode(StrEnum):
    """Machine-readable failure/condition codes for supervisor decisions.

    Reuses existing taxonomies where they exist (intervention kinds,
    live-runner stop reasons, submission result states are mapped onto
    these codes by :mod:`universal_auto_applier.supervisor.policy`).
    """

    CAPTCHA = "captcha"
    LOGIN_REQUIRED = "login_required"
    TWO_FACTOR_REQUIRED = "two_factor_required"
    IDENTITY_VERIFICATION = "identity_verification"
    MISSING_FACT = "missing_fact"
    UNKNOWN_REQUIRED_FIELD = "unknown_required_field"
    UNSUPPORTED_WIDGET = "unsupported_widget"
    DOCUMENT_PROBLEM = "document_problem"
    DOCUMENT_INPUT_NOT_MULTIPLE = "document_input_not_multiple"
    NO_SAFE_NAVIGATION = "no_safe_navigation"
    ATS_CHANGED = "ats_changed"
    APPLICATION_EXPIRED = "application_expired"
    APPLICATION_ALREADY_SUBMITTED = "application_already_submitted"
    DUPLICATE_APPLICATION = "duplicate_application"
    INTERVENTION_REQUIRED = "intervention_required"
    RETRYABLE_EXECUTION_FAILURE = "retryable_execution_failure"
    UAA_MAPPING_DEFECT = "uaa_mapping_defect"
    UAA_EXECUTION_DEFECT = "uaa_execution_defect"
    COOKIE_CONSENT_BLOCKED = "cookie_consent_blocked"
    COOKIE_CONSENT_RESOLVED = "cookie_consent_resolved"
    REVIEW_READY = "review_ready"
    DOCUMENT_LINEAGE_MISMATCH = "document_lineage_mismatch"
    DEDICATED_SIEMENS_WORKFLOW = "dedicated_siemens_workflow"
    UNKNOWN_FAILURE = "unknown_failure"


class SupervisorDecision(BaseModel):
    """A typed, validated supervisor decision.

    Model output MUST be parsed into this schema; anything that does not
    validate fails closed (the planner returns ``REQUEST_HUMAN``). The
    action is an enum — arbitrary tool names generated by a model are
    impossible to express.
    """

    model_config = ConfigDict(frozen=True)

    action: SupervisorAction
    application_id: str = Field(min_length=1)
    intervention_id: str | None = None
    reason_code: ReasonCode = ReasonCode.UNKNOWN_FAILURE
    rationale: str = ""
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    answer: str | None = None
    answer_source: AnswerSource | None = None
    save_to_memory: bool = False
    retry_allowed: bool = False

    @field_validator("application_id")
    @classmethod
    def _strip_application_id(cls, value: str) -> str:
        value = value.strip()
        if not value:
            raise ValueError("application_id must not be empty")
        return value

    def is_valid_for_execution(self) -> bool:
        """Structural pre-checks before the service executes a decision."""
        if self.action is SupervisorAction.RESOLVE_INTERVENTION:
            return (
                bool(self.intervention_id)
                and self.answer is not None
                and self.answer_source is not None
            )
        if self.action is SupervisorAction.REQUEST_HUMAN:
            return True
        return True


class SupervisorLimits(BaseModel):
    """Conservative bounded-retry configuration (no infinite loops)."""

    model_config = ConfigDict(frozen=True)

    max_application_attempts: int = Field(default=2, ge=1)
    max_intervention_resolutions: int = Field(default=3, ge=1)
    max_same_failure_retries: int = Field(default=2, ge=1)


class OwnerPolicy(BaseModel):
    """One reusable owner-approved decision (knowledge level 2).

    Loaded from a local JSON file supplied by the owner — never invented by
    the model. ``normalized_question`` is matched exactly (same
    normalization as AnswerMemory) against a pending field label/question.
    """

    model_config = ConfigDict(frozen=True)

    policy_id: str = Field(min_length=1)
    normalized_question: str = Field(min_length=1)
    answer: str = Field(min_length=1)
    description: str = ""


class InterventionView(BaseModel):
    """Sanitized, decision-relevant view of a pending intervention.

    Only the information needed for a decision — no filled values, no
    screenshots, no page HTML.
    """

    model_config = ConfigDict(frozen=True)

    intervention_id: str
    kind: str
    question: str
    field_label: str | None = None
    field_type: str | None = None
    options: list[str] = Field(default_factory=list[str])
    reason: str | None = None
    required: bool = True
    suggested_answer: str | None = None
    confidence: float | None = None
    risk_level: str | None = None
    category: str | None = None


class PlannerContext(BaseModel):
    """Everything a planner may see when deciding on one application.

    Deliberately bounded: job metadata fields relevant for decisions, the
    pending interventions (sanitized), retry counters, and the known
    candidate-fact keys (names only, never values) so a planner can detect
    a mapping defect without receiving PII.
    """

    model_config = ConfigDict(frozen=True)

    application_id: str
    company: str = ""
    title: str = ""
    platform: str = ""
    job_status: str = ""
    supervisor_state: SupervisorState = SupervisorState.IMPORTED
    interventions: list[InterventionView] = Field(default_factory=list[InterventionView])
    unresolved_required_field_count: int = 0
    pending_intervention_count: int = 0
    prepare_attempts: int = 0
    intervention_resolutions: int = 0
    last_reason_code: str | None = None
    same_failure_count: int = 0
    candidate_fact_keys: list[str] = Field(default_factory=list[str])


class SupervisorRunSummary(BaseModel):
    """Structured end-of-run summary (JSON + readable CLI output)."""

    run_id: str
    imported: int = 0
    skipped_siemens: int = 0
    review_ready: list[str] = Field(default_factory=list[str])
    needs_human: list[dict[str, str]] = Field(default_factory=list[dict[str, str]])
    repair_needed: list[dict[str, str]] = Field(default_factory=list[dict[str, str]])
    skipped: list[dict[str, str]] = Field(default_factory=list[dict[str, str]])
    failed: list[dict[str, str]] = Field(default_factory=list[dict[str, str]])
    submission_attempts: int = 0


__all__ = [
    "AnswerSource",
    "InterventionView",
    "OwnerPolicy",
    "PlannerContext",
    "ReasonCode",
    "SupervisorAction",
    "SupervisorDecision",
    "SupervisorLimits",
    "SupervisorRunSummary",
    "SupervisorState",
]
